# Generated by Django 2.1.7 on 2019-03-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finance',
            old_name='post',
            new_name='description',
        ),
    ]
