# Generated by Django 2.1.7 on 2019-03-24 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20190324_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finance_category', models.IntegerField(verbose_name='Categories')),
                ('category_description', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='finance',
            options={'verbose_name_plural': 'Finance'},
        ),
        migrations.AddField(
            model_name='finance',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='finance.FinanceCategory', verbose_name='Catefory'),
        ),
    ]
