# Generated by Django 2.1.7 on 2019-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_auto_20190324_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='type',
            field=models.CharField(max_length=80),
        ),
        migrations.DeleteModel(
            name='FinanceCategory',
        ),
    ]
